### ISSUE TITLE
Hyperlinks to be added

### ISSUE THREAD

**Issue by julieckim** [ktakahata/grainger#10]
p. 5, fn. 41: hyperlink added to individual page file but still needs to be added to file with all pages
p. 94, fn. 421: two hyperlinks that need to be added both to the individual page and to the file with all pages
p. 129, fn. 581: hyperlink that needs to be added both to the individual page and to the file with all pages
p. 158, fn. 720: hyperlink added to individual page file but still needs to be added to file with all pages

**Comment by ktakahata** [comment]
Added link language in individual and full page files for all instances listed above
