### ISSUE TITLE
internal links

### ISSUE THREAD

**Issue by ktakahata** [ktakahata/grainger#15]
Can we do them? ie link from one footnote to another?

**Comment by elotroalex** [comment]
We might be able with html. Try with this one https://www.yourhtmlsource.com/text/internallinks.html, or let me know which footnotes if it's only a few.

**Comment by ktakahata** [comment]
I've inserted links whenever we gesture to another note or when Grainger cites himself, which means that in some instances, I've included links directly into the transcribed text. The only exclusion is on page 18 when Grainger says "see Book III" in reference to quick-lime, where I did not include a link because of his later prolonged discussion. If we'd prefer to leave Grainger's text untouched, I can also remove those links.

**Comment by elotroalex** [comment]
or you can signal through font or color that you are making an addition. as
long as you are transparent, either in the text or in the editorial note,
all sins are forgiven

**Comment by ktakahata** [comment]
They currently look like other links (red and underlined when you hover), so we should be good!
