### ISSUE TITLE
Placement of sidebar button

### ISSUE THREAD

**Issue by julieckim** [ktakahata/grainger#19]
Ok, this is being super picky, so if it's really hard, it's okay not to do. But would it be possible to move the sidebar button down a smidgen so that it is level with or slightly below the "Digital Grainger" title on the homepage (and other pages)? Right now, it's slightly above, and I feel it's a little disruptive visually (I'd prefer that "Digital Grainger" is the "highest" thing on each page).

**Comment by julieckim** [comment]
Also, with this comment, I'm talking solely about the version of the site that shows up on a computer or larger-screened device. I'm fine with the sidebar button being the "highest" element on the mobile version.

**Comment by ktakahata** [comment]
Increased padding on sidebar so that it is level with "Digital Grainger" title
