### ISSUE TITLE
Sidebar button disappears in certain situations

### ISSUE THREAD

**Issue by julieckim** [ktakahata/grainger#21]
This one I suspect is hard to fix and doesn't absolutely need to be done. But I noticed while testing the site on my phone that if you click on the sidebar on a page like "Full Text" and then jump to "Book III," there is no way to close the sidebar and actually read the poem because the sidebar button has disappeared.

**Comment by ktakahata** [comment]
The easiest way to fix it would be to have the sidebar button shift down as you scroll on those pages, but it would then awkwardly cover up the text in the upper lefthand corner. Alex, would be able to do something like https://www.washingtonpost.com/ mobile version where the header scrolls with you when we view the site on the phone?

**Comment by elotroalex** [comment]
I designed it to disappear on purpose.

It would be possible to do what you want but it would take a good 2-3 hour
of research and work. Want to give it a try? I created a set of
instructions already for just mobile. You would need to make it absolute
and maybe add a couple of other lines. You might have to hide the subtitle
if you want this to be a solution just with CSS. If you want it to be just
like the washington post you'd need some javascript for that. I haven't
trained you in that yet, but it might be a copy and paste solution that you
find where you just have to change a few things that you will recognize by
reading closely what is in the javascript.

**Comment by ktakahata** [comment]
I can take a look--I've been trying to just add a "close menu" button (or an x in the menu itself), but I've been having trouble finding anything that's pure CSS that works

**Comment by elotroalex** [comment]
I would leave as is. The need to use the menu lessens when you start
reading, and going back up is easy, no?

**Comment by ktakahata** [comment]
The only issue is on a phone after you've jumped to the new spot--because the menu button disappears, there's no way to close the menu and read. Once it's closed, the need for the menu button definitely lessens

**Comment by elotroalex** [comment]
Hm. Thst does sound like a problem. I'll find time to solve this week. Can
we delay launch?

**Comment by julieckim** [comment]
Dear Alex,

Thanks for working on this issue, and it would not be a problem to delay launch. The excerpts still need some more revision (as do a few of the other pages), so we need 2-3 weeks to take care of that. And I think it would be better to wait for the jump-to function to be ready before launching anyway. So let’s aim for end of this month (Oct). I’m cc’ing Cristobal here in case he has a preference that is different, but I think we are agreed that it would be okay to wait for about another month. 

All the best,
Julie

**Comment by julieckim** [comment]
Sounds good to me. I got the ball rolling.

**Comment by ktakahata** [comment]
The other option I've been looking into is just adding a "close menu" or an x button on the mobile menu. Will keep looking, but wanted to update

**Comment by julieckim** [comment]
Thanks, Kimberly! I think that would be perfectly sufficient. And I will get back to you soon re: the bibliography and other things. Am planning to dedicate some time to Grainger this weekend. 

Julie

**Comment by ktakahata** [comment]
Added command to javascript that collapses sidebar once option is selected
