### ISSUE TITLE
Create Jump-To feature

### ISSUE THREAD

**Issue by elotroalex** [ktakahata/grainger#26]
This will appear in the bottom of the page-by-page view next to the prev | next links. We imagine a box were you type a page # and then hit enter and voila. @ktakahata correct me if I'm wrong.

**Comment by mnyrop** [comment]
@elotroalex I don't follow. Can you describe in more detail? e.g., 
What page(s)? 
What data is being pulled in?
How should it 'move' (i.e., does it open new pages, scroll down or use jquery to update contents)  ?
etc ?

**Comment by elotroalex** [comment]
When you go to [this page](https://ktakahata.github.io/grainger/paginated/sc-first_pages_front_1.html) you will notice a `Prev | Next` in the bottom. The form box for `Jump to` should be next to it. When you hit enter it should simply go to the page with that number. The values for pages for are in the `order` key in the YAML header for each of these pages.

**Comment by mnyrop** [comment]
@elotroalex its should jump within a Mirador viewer? Or actually open another html page?

**Comment by elotroalex** [comment]
Just open another html page. Ez-pz

**Comment by ktakahata** [comment]
Check if embedded images will load on 2G (Alex)
If it does, shift image below transcribed text
If it doesn't, keep image only as a link on the page title

**Comment by ktakahata** [comment]
image didn't load on 2G; removed embedded image from page-item layout
