### ISSUE TITLE
notes from launch meeting

### ISSUE THREAD

**Issue by ktakahata** [ktakahata/grainger#9]
1. page by page broken (Alex, Kimberly)
2. Zotero html and reformatting in Ed (Cristobal, Steve, Alex)
3. put MLA citation in menu and delete "Using this cite" (Kimberly)
4. Special sidebar for Front Matter, Preface Books I, II, III, IV, End Matter in full page version (look at example on Ed, Frederick Douglass) put in yaml header (Kimberly)
5. fix external links in full text (make all different window) and centerings on full text file (Kimberly)
6. lines after footnotes and before prev/next (Alex)
7. can we do internal links? (Alex)
8. links to excerpts (Kimberly)
9. About/Poetry and Slavery (Julie and Cristobal)

**Comment by elotroalex** [comment]
fixed by link in front page, no? can you close it?

**Comment by ktakahata** [comment]
3. added MLA citation in sidebar file
4. see further question re: special sidebar in issues; added for Glossary through sidebar-toc file
5. added code in both full text and page by page
6. see separate issue
7. see separate issue
8. see separate issue
9. see "pages that need text"
